version: '3'
services:
    reverseproxy:
        image: nginx:alpine
        container_name: reverse-proxy
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /private/etc/letsencrypt/live/femh.tsai.it/fullchain.pem:/etc/letsencrypt/live/femh.tsai.it/fullchain.pem
            - /private/etc/letsencrypt/live/femh.tsai.it/privkey.pem:/etc/letsencrypt/live/femh.tsai.it/privkey.pem
        ports:
            - 80:80
            - 443:443
        networks:
            - nginx-network

    ris-flask:
        depends_on:
            - reverseproxy
        image: tsaiid/ris-flask
        container_name: ris-flask
        expose:
            - "8000"
        volumes:
            - /Users/tsaiid/git/femh-ris/config:/app/config
        networks:
            - nginx-network

    cxr-ai-flask:
        depends_on:
            - reverseproxy
        image: tsaiid/cxr-ai-flask
        container_name: cxr-ai-flask
        expose:
            - "8000"
        volumes:
            - /Users/tsaiid/git/femh-dicom/config:/app/config
        networks:
            - nginx-network

networks:
    nginx-network:
